name: check
on: [push]
     
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test  
      
      - name: lint code
        run: yarn run lint

      - name: Build
        run: yarn run build 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build 